# Generated by Django 5.2.12 on 2026-04-02 06:46

import apis.authentication.choices
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mqtt_topic', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by_%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
            },
        ),
        migrations.CreateModel(
            name='TokenACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='allow', max_length=10)),
                ('action', models.CharField(choices=[('publish', 'Publish'), ('subscribe', 'Subscribe'), ('all', 'All')], default='all', max_length=10)),
                ('topic', models.CharField(help_text='MQTT topic เช่น swd/sensor/+/data หรือใช้ wildcard + และ #', max_length=255)),
                ('qos', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'QoS 0 - At most once'), (1, 'QoS 1 - At least once'), (2, 'QoS 2 - Exactly once')]), default=apis.authentication.choices.ACLQoS.default_qos, size=None)),
                ('retain', models.BooleanField(default=False)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='authentication.devicetoken')),
            ],
            options={
                'verbose_name': 'Token ACL',
                'verbose_name_plural': 'Token ACLs',
                'unique_together': {('device_token', 'action', 'topic')},
            },
        ),
    ]
