# Generated by Django 5.2.12 on 2026-03-19 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('template_message', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('tool', models.CharField(choices=[('auth', 'Auth')])),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('access', 'Access')])),
                ('changes', models.JSONField(null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='actor_historylogs', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedValueAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_format', models.TextField()),
                ('object_id', models.PositiveBigIntegerField(null=True)),
                ('default_value', models.TextField(default='')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log', to='general.auditlog')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype')),
            ],
        ),
    ]
